### PR TITLE
SSLRSQBR-70 Drop unused code

### PR DESCRIPTION
**Pull request by m-g-sonar**
The following code has been removed:

- math package
- common rules package
- text package
- entire squid index logic
- hardcoded list of tags for rules

The following plugins are still using sslr-squid-bridge, but none of the code listed above is depending on it anymore:

- abap
- flex
- java
- php
- swift
- vb
- web

The following plugins are not depending on sslr-squid-bridge:

- pli
- plsql
- python
- rpg
- tsql
- xml

The following plugins have not been checked:

- cobol
- javascript
- typescript
- cpp

### CODE REVIEW

**Comment by nixel2007** [comment]
What is a replacement for squid logic? My plugin counts on AstScanner and all of this SourceFunction/SourceFile stuff...

**Comment by m-g-sonar** [comment]
@nixel2007 There is no library provided as direct replacement nor equivalent. This code is old, and relies mainly on code which is itself not supported by SonarQube latest LTS, or not maintained anymore. We moved away from it in all our analyzers during the last weeks.

The best way to move away from squid index would be to rewrite your own logic for checks, the way we did it for multiple plugins. It most probably implies rewriting highlighting and some small parts on all the rules, which was handling the "subscription" logic. It also implies rewriting the metrics.

You may want to have a look at this PR as a good example, as well as the other PR which have been recently closed: [SONARFLEX-105 Stop using squid index](https://github.com/SonarSource/sonar-flex/pull/39)

You may of course choose to stay with previous versions of sslr-squid-bridge, but it is not going to be updated to support latest SQ LTS.

**Comment by nixel2007** [comment]
@m-g-sonar thanks for reply, I'll check that link.

**Comment by m-g-sonar** [comment]
@nixel2007 don't hesitate to ask (maybe in our mailing list) if you have any questions regarding moving away from sslr-squid-bridge. We did it multiple times recently, and we have most probably encountered similar situations.

**Pull request merged**
